import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiExpress,
  SiTailwindcss,
  SiMongodb,
  SiPostgresql,
  SiVercel,
  SiGit,
  SiGithub,
  SiFramer,
  SiJest,
  SiMocha,
  SiChai,
  SiSelenium,
  SiSass,
  SiRedis,
  SiSocketdotio,
  SiPrisma,
  SiZod,
  SiHtml5,
  SiAppwrite,
  SiJsonwebtokens,
  SiReactrouter,
  SiC,
  SiXyflow,
  SiTanstack,
  SiPostman,
  SiFigma,
} from "react-icons/si";

/** Canonical icon key -> brand icon component. */
const iconRegistry: Record<string, IconType> = {
  react: SiReact,
  nextjs: SiNextdotjs,
  typescript: SiTypescript,
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  express: SiExpress,
  tailwind: SiTailwindcss,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  vercel: SiVercel,
  git: SiGit,
  github: SiGithub,
  framer: SiFramer,
  jest: SiJest,
  mocha: SiMocha,
  chai: SiChai,
  selenium: SiSelenium,
  sass: SiSass,
  redis: SiRedis,
  socketio: SiSocketdotio,
  prisma: SiPrisma,
  zod: SiZod,
  html5: SiHtml5,
  appwrite: SiAppwrite,
  jwt: SiJsonwebtokens,
  reactrouter: SiReactrouter,
  c: SiC,
  reactflow: SiXyflow,
  tanstack: SiTanstack,
  postman: SiPostman,
  figma: SiFigma,
};

/** Ordered `[pattern, key]` pairs — first match wins, so put specific patterns before broad ones. */
const aliasPatterns: [RegExp, string][] = [
  [/next\.?js/i, "nextjs"],
  [/react[\s-]?flow|xyflow/i, "reactflow"],
  [/react\s*router/i, "reactrouter"],
  [/react(\.js)?$|reactjs/i, "react"],
  [/typescript|^ts$/i, "typescript"],
  [/javascript|^js$|es6/i, "javascript"],
  [/node(\.js)?/i, "nodejs"],
  [/express(\.js)?/i, "express"],
  [/tailwind/i, "tailwind"],
  [/mongodb/i, "mongodb"],
  [/postgres/i, "postgresql"],
  [/vercel/i, "vercel"],
  [/github/i, "github"],
  [/^git$|git\s*\/\s*github/i, "git"],
  [/framer/i, "framer"],
  [/jest/i, "jest"],
  [/mocha/i, "mocha"],
  [/chai/i, "chai"],
  [/selenium/i, "selenium"],
  [/sass|scss/i, "sass"],
  [/redis/i, "redis"],
  [/socket\.?io/i, "socketio"],
  [/prisma/i, "prisma"],
  [/^zod$/i, "zod"],
  [/html5|html/i, "html5"],
  [/appwrite/i, "appwrite"],
  [/jwt|json web token/i, "jwt"],
  [/tanstack/i, "tanstack"],
  [/postman/i, "postman"],
  [/figma/i, "figma"],
  [/^c$/i, "c"],
];

/** Resolves a free-text tech/language name (e.g. "Next.js 14", "React.js") to a brand icon, if one exists. */
export function getTechIcon(name: string): IconType | null {
  const trimmed = name.trim();
  for (const [pattern, key] of aliasPatterns) {
    if (pattern.test(trimmed)) return iconRegistry[key] ?? null;
  }
  return null;
}
